"""
Minimal GitHub webhook receiver.

Listens for GitHub's "push" webhook event and immediately runs
auto-update.sh - no polling, no waiting on a timer. Uses only Python's
standard library (no new dependency needed).

Security: GitHub signs every webhook delivery with an HMAC-SHA256
signature of the raw request body, using a secret both sides know (see
https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries).
Every request is checked against WEBHOOK_SECRET (from webhook_secret.txt,
generated by setup-autoupdate.sh) before anything runs. Requests that
don't have a valid signature are rejected with 401 and ignored - so
exposing this port to the internet is safe as long as the secret stays
private.
"""

import hashlib
import hmac
import json
import logging
import os
import subprocess
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] webhook: %(message)s")
log = logging.getLogger("webhook")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SECRET_PATH = os.path.join(SCRIPT_DIR, "webhook_secret.txt")
UPDATE_SCRIPT = os.path.join(SCRIPT_DIR, "auto-update.sh")


def load_secret() -> str:
    if not os.path.exists(SECRET_PATH):
        sys.exit(f"{SECRET_PATH} not found - run setup-autoupdate.sh first.")
    with open(SECRET_PATH, "r", encoding="utf-8") as f:
        secret = f.read().strip()
    if not secret:
        sys.exit(f"{SECRET_PATH} is empty - run setup-autoupdate.sh again.")
    return secret


SECRET = load_secret()
PORT = int(os.environ.get("WEBHOOK_PORT", "9001"))


def verify_signature(body: bytes, signature_header: str) -> bool:
    if not signature_header or not signature_header.startswith("sha256="):
        return False
    expected = "sha256=" + hmac.new(SECRET.encode(), body, hashlib.sha256).hexdigest()
    # constant-time comparison - avoids leaking the secret via response-timing
    return hmac.compare_digest(expected, signature_header)


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        log.info("%s - %s", self.address_string(), fmt % args)

    def _reply(self, code: int, text: bytes = b""):
        self.send_response(code)
        self.end_headers()
        if text:
            self.wfile.write(text)

    def do_GET(self):
        # Handy for a quick "is this even reachable" check from a browser.
        self._reply(200, b"tf2-deal-watcher webhook listener is running")

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length) if length else b""
        signature = self.headers.get("X-Hub-Signature-256", "")

        if not verify_signature(body, signature):
            log.warning("Rejected webhook delivery: missing/invalid signature.")
            self._reply(401, b"invalid signature")
            return

        event = self.headers.get("X-GitHub-Event", "")

        if event == "ping":
            log.info("GitHub ping received - webhook is correctly configured.")
            self._reply(200, b"pong")
            return

        if event != "push":
            log.info("Ignoring non-push event: %s", event)
            self._reply(200, b"ignored")
            return

        try:
            payload = json.loads(body) if body else {}
            ref = payload.get("ref", "")
        except Exception:
            ref = ""

        if ref and not (ref.endswith("/main") or ref.endswith("/master")):
            log.info("Ignoring push to %s (not main/master).", ref)
            self._reply(200, b"ignored (not main/master)")
            return

        log.info("Valid push received - triggering update.")
        self._reply(200, b"ok, updating")
        # Respond first, then update in the background so GitHub's webhook
        # delivery doesn't have to wait on the git pull + service restart.
        subprocess.Popen(["bash", UPDATE_SCRIPT])


def main():
    server = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    log.info("Webhook listener running on port %d (POST /webhook from GitHub)", PORT)
    server.serve_forever()


if __name__ == "__main__":
    main()
